/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyecto_poo_mathkids;

/**
 *
 * @author Gabriel
 */
public class PanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlblUsuario = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jtxtUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jpasswordContraseña = new javax.swing.JPasswordField();
        jbtnIngresar = new javax.swing.JButton();
        jlblContraseña = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlblUsuario.setBackground(new java.awt.Color(0, 0, 0));
        jlblUsuario.setText("USUARIO");
        jPanel1.add(jlblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 50, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jtxtUser.setText("INGRESE SU USUARIO");
        jtxtUser.setBorder(null);
        jtxtUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtxtUserMousePressed(evt);
            }
        });
        jtxtUser.addActionListener(this::jtxtUserActionPerformed);
        jPanel1.add(jtxtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 260, -1));

        jLabel3.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("INICIAR SESION");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 60));

        jButton3.setText("REGISTRARSE ALUMNO");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 380, 170, -1));

        jpasswordContraseña.setText("********");
        jpasswordContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jpasswordContraseñaMousePressed(evt);
            }
        });
        jpasswordContraseña.addActionListener(this::jpasswordContraseñaActionPerformed);
        jPanel1.add(jpasswordContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 260, 20));

        jbtnIngresar.setText("INGRESAR");
        jPanel1.add(jbtnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, -1));

        jlblContraseña.setBackground(new java.awt.Color(0, 0, 0));
        jlblContraseña.setText("CONTRASEÑA");
        jPanel1.add(jlblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 30));

        jButton1.setText("REGISTRARSE PROFESOR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUserActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
 
    java.awt.Container contenedor = this.getParent();
    
    if (contenedor != null && contenedor.getLayout() instanceof java.awt.CardLayout) {
        java.awt.CardLayout cl = (java.awt.CardLayout) contenedor.getLayout();
        
        // Viajamos a la tarjeta del registro de alumnos
        cl.show(contenedor, "cardRegistro");
    }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jpasswordContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordContraseñaActionPerformed
     
        
    }//GEN-LAST:event_jpasswordContraseñaActionPerformed

    private void jtxtUserMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtxtUserMousePressed
        jtxtUser.setText("");
        jpasswordContraseña.setText("********");
        
    }//GEN-LAST:event_jtxtUserMousePressed

    private void jpasswordContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpasswordContraseñaMousePressed
        jtxtUser.setText("Ingrese su Usuario");
        jpasswordContraseña.setText("");
        
    }//GEN-LAST:event_jpasswordContraseñaMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.awt.Container contenedor = this.getParent();
    
    if (contenedor != null && contenedor.getLayout() instanceof java.awt.CardLayout) {
        java.awt.CardLayout cl = (java.awt.CardLayout) contenedor.getLayout();
        

        cl.show(contenedor, "cardProfesor");
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtnIngresar;
    private javax.swing.JLabel jlblContraseña;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JPasswordField jpasswordContraseña;
    private javax.swing.JTextField jtxtUser;
    // End of variables declaration//GEN-END:variables
}
